language: groovy
#gradle doesn't have a retry for assembling dependencies so here's one in bash
install: ./assemble.sh
script:
  - ./gradlew clean check Jar
branches:
  only:
    - master
    - jervis_simple
#https://docs.travis-ci.com/user/languages/groovy#caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jenkins:
  pipeline_jenkinsfile: assets/Jenkinsfile
  collect:
    artifacts: build/libs/*.jar
    junit: build/test-results/*.xml
